import { all } from "../../../node_modules/@types/q";

export const language = {
    "personal_information": "Información personal",
    "code": "Código",
    "identification": "Cedula",
    "name": "Nombre",
    "last_name": "Apellido",
    "phone":"Teléfono",
    "address":"Dirección",
    "birth_date":"Fecha nacimiento",
    "civil_status":"Estado civil",
    "company":"Empresa",
    "classification":"Clasificación",
    "cell_phone":"Celular",
    "contract":"Contrato",
    "t_contract":"T contrato",
    "account_type": "Tipo cuenta",
    "save":"Guardar",
    "delete":"Eliminar",
    "update":"Actualizar",
    "modification":"Modificar",
    "store":"Almacén",
    "inventory":"Inventario",
    "materials":"Materiales",
    "description":"Descripción",
    "unity":"Unidad",
    "status":"Estado",
    "kind_input":"Tipo Insumo",
    "min_inventory":"Min Inventario",
    "average_value":"Valor Promedio",
    "iva":"Iva",
    "control_series":"Control Series",
    "purchase":"Compras",
    "purchase_order":"Orden Compra",
    "provider":"Proveedor",
    "date":"Fecha",
    "deliver_date":"Fecha Entrega",
    "observations":"Observaciones",
    "to_print":"Imprimir",
    "search":"Buscar",
    "can_requested":"Can Solicitada",
    "can_received":"Can Recibida",
    "value_uni":"Valor Uni",
    "desc":"Desc",
    "v_with_iva":"V con Iva",
    "subtotal":"SubTotal",
    "total":"Total",
    "start_date":"Fecha Inicial",
    "finish_date":"Fecha Final",
    "consult":"consultar",
    "selection":"Selección",
    "n_entry":"N° Ingreso",
    "n_order":"N° Orden",
    "close":"Cerrar",
    "movement":"Movimiento",
    "cellar":"Bodega",
    "admission_date":"Fecha Ingreso",
    "N_Invoice":"N° Factura",
    "nro":"Nro",
    "Remission":"N° Remisión",
    "state_order":"Estado Orden",
    "edit":"Editar",
    "dispatches":"Despachos",
    "destination":"Destino",
    "stratum":"Estrato",
    "type_work":"Tipo Obra",
    "consecutive":"Consecutivo",
    "consecutive_work":"Consecutivo Obra",
    "oti":"OTI",
    "in_charge":"Encargado",
    "plane_number":"Numero De plano",
    "Observations":"Observaciones",
    "item":"Item",
    "quantity":"Cantidad",
    "reintegos":"Reintegos",
    "stock":"Existencias",
    "series":"Series",
    "refunds":"Reintegros",
    "missing":"Faltante",
    "search_massive":"Buscar Masivos",
    "reintegrate":"Reintegrar",
    "employee":"Empleado",
    "material":"Material",
    "selectionar":"Seleccionar",
    "transfers":"Traslados",
    "warehouse_origin":"Almacen/Origen",
    "warehouse_destination":"Almacen/Destino",
    "destination_warehouse":"Almacen Destino",
    "serial_number":"Numero Serie",
    "add_meter":"Agregar Medidor",
    "kind":"Tipo",
    "brand":"Marca",
    "lote":"Lote",
    "Delivery":"Delivery",
    "box":"Caja",
    "available":"Disponible",
    "dispatched":"Despachado",
    "Installed":"Instalado",
    "delivery":"Entrega",
    "item_charged":"Items de Cobro",
    "new":"Nuevo",
    "value":"Valor",
    "create_item":"Crear Item",
    "item_code":"Código Item",
    "description_item":"Descripción Item",
    "unit_item":"Unidad Ítem",
    "item_value":"Valor Ítem",
    "item_status":"Estado Ítem",
    "type_input":"Tipo De insumo",
    "classification_item":"Clasificación Ítem",
    "activities":"ACTIVIDADES",
    "action":"Acción",
    "create_activity":"Crear Actividad",
    "activity_description":"Descripción Actividad",
    "download_documents_EPM":"Descargar Documentos-EPM",
    "contracts":"Contratos",
    "month":"Mes",
    "download":"Descargar",
    "internal_search":"Internas Buscar",
    "work":"Obra",
    "details":"Detalles",
    "complaints":"Quejas",
    "external_search":"Externas Buscar",
    "operations_search":"Operaciones Buscar",
    "programming":"Programación",
    "program":"Programar",
    "travel":"RECORRIDO",
    "work_programmed":"OBRA POR PROGRAMADA",
    "programmed_work":"OBRA PROGRAMADA",
    "date_re":"Fecha Re",
    "linesman":"Recorredor",
    "schedule_to":"Programar a",
    "programming_date":"Fecha de Programación",
    "municipality":"Municipio",
    "cod_installation":"Cod Instalación",
    "applicant":"Solicitante",
    "tel_installation":"Tel Instalacion",
    "tel_contact":"Tel Contacto",
    "zone":"Zona",
    "upload_work":"Subir Obra",
    "import":"Importar",
    "mistakes":"Errores",
    "order":"Pedido",
    "ot":"Ot",
    "customer_data":"Dto Cliente",
    "client_name":"Nombre Cliente",
    "customer_tel":"Tel Cliente",
    "Valve":"Válvula",
    "x":"x",
    "y":"y",
    "sub_type_work":"Sub tipo de obra",
    "result":"Resultado",
    "sub_type":"Sub Tipo",
    "payment_activities":"Pago de Actividades",
    "state_work":"Estado Obra",
    "position":"Cargo",
    "payment_status":"Estado Pago",
    "point_value":"Valor Punto",
    "other_payments":"Otros Pagos",
    "payment_id":"ID Pago",
    "goal":"Meta",
    "balance":"Saldo",
    "other_desc":"Otros Desc",
    "discount":"Descuento",
    "total_pay":"Total a Pagar",
    "loans":"Préstamos",
    "pay":"Pagar",
    "payments":"Pagos",
    "payment_consultation":"Consulta de Pagos",
    "see_details":"Ver Detalles",
    "state_requested":"Estado Pedido",
    "active_value":"Valor Activi",
    "activity_status":"Estado Actividad",
    "work_printing":"IMPRESION DE OBRA",
    "settlement":"LIQUIDACIÓN",
    "fc":"FC",
    "user":"Usuario",
    "date_assignment":"Fecha Asignación",
    "search_programation":"Buscar Programación",
    "employee_name":"Nombre Empleado",
    "archive":"Archivo",
    "preact":"Preacta",
    "download_EXCEL":"Descargar EXCEL",
    "minutes":"Acta",
    "paid_out":"Pagado",
    "top_payment":"Pago superior",
    "partial_payment":"Pago parcial ",
    "existent_payment":"Pago Inexistente",
    "sex":"Sexo",
    "age":"Edad",
    "entity":"Entidad",
    "account":"Cuenta",
    "endowment":"Ver Dotación",
    "additional_information":"Información Complementaria",
    "Department":"Departamento",
    "municipality_labor":"Municipio Labor",
    "education_level":"Nivel Educativo",
    "eps":"EPS",
    "sub_position":"Sub Cargo",
    "crews":"Cuadrillas",
    "final_risk_level":"Nivel de Riesgo Final",
    "arl":"ARL",
    "pensions":"Pensiones",
    "create_contract":"Crear contrato",
    "see_contracts":"Ver contratos",
    "salary":"Salario",
    "aux_remoteness":"Aux lejanía",
    "aux_bearing":"Aux rodamiento",
    "Bonus":"Bonificación",
    "reason_completion":"Motivo Finalización",
    "contract_id":"ID contrato",
    "type_contract":"Tipo Contrato",
    "remote_assistance":"Auxilio Lejanía",
    "help_bearing":"Auxilio por Rodamiento",
    "fixed_bonus":"Bonificación Fija",
    "eendowment":"Dotación",
    "disciplinary_processes":"Procesos Disciplinarios",
    "permits_suspensions":"Permisos & Suspenciones",
    "document":"Documento",
    "permissions":"Permisos",
    "permission_concept":"Concepto Permiso",
    "days_suspension":"Dias de Suspensión",
    "add":"Agregar",
    "concept":"Concepto",
    "absenteeism":"Ausentismo",
    "details_suspension":"Detalles Suspensión",
    "suspension_days":"Dias Suspension",
    "permits":"Permisos",
    "name_profile":"Nombre Perfil",
    "submenu":"Submenú",
    "internal":"Internas",
    "collection_items":"Items de cobro",
    "events":"Eventos",
    "external":"Externas",
    "budget":"Presupuesto",
    "construction_report":"Informe de Obra",
    "contracts_employees":"Contratos Empleados",
    "create_contracts":"Crear Contratos",
    "edit_contract":"Editar Contrato",
    "registration_date":"Fecha Registro",
    "nit_id":"Nit ID",
    "digit":"Dígito",
    "email":"E-mail",
    "fax":"Fax",
    "extension":"Extensión",
    "contact_name":"Nombre Contato",
    "update_provider":"Actualizar Proveedor",
    "add_material":"Agregar Material",
    "unitary":"V Unitario",
    "v_total":"V Total",
    "v_with_Discount":"V con Descuento",
    "add_materials":"Agregar Materiales",
    "search_provider":"Buscar proveedor",
    "nit":"Nit",
    "edit_material":"Editar Material",
    "material_code":"Código Material",
    "id":"ID",
    "contract_name":"Nombre Contrato",
    "director":"Director",
    "update_contract":"Actualizar Contrato",
    "save_contract":"Guardar Contrato",
    "create_company":"Crear Empresa",
    "logo":"Logo",
    "create_warehouse":"Crear Bodega",
    "select_company":"Seleccione Empresa",
    "warehouse_name":"Nombre Almacen",
    "warehouse_management":"Direccion Almacen",
    "":"",

}


